### ISSUE TITLE
Y2 label getting truncated when hasCustomPadding is true.

### ISSUE THREAD

**Issue by pranav300** [cerner/carbon-graphs#110]
**Describe the bug**
 Y2-axis label is getting truncated when `hasCustomPadding`
 is true.

**To Reproduce**

1. Go to the code and add custom padding to [this](https://github.com/cerner/carbon-graphs/blob/master/dev/examples/controls/line.js#L34) similar to that in constants.
3. run the local server
4. Go to this link http://localhost:9991/#/line/y2-axis

**Expected behavior**
Y2-axis label should be visible with hasCustomProperty.

**Screenshots**
<img width="1366" alt="Screenshot 2019-11-12 at 3 27 31 PM" src="https://user-images.githubusercontent.com/29273628/68677263-cc04ad00-0581-11ea-9295-97298f1f8079.png">

**Desktop (please complete the following information):**

-   OS: IOS
-   Browser: Chrome

**Comment by abhijit945** [comment]
A little background is needed here. Would this behavior show up when you just set the padding property and dont send in any values? 
If you are using the padding property then you sure expect the items outside the content can move away from the screen.

**Comment by pranav300** [comment]
> A little background is needed here. Would this behavior show up when you just set the padding property and don't send in any values?
yes, And even when I am passing values in custom padding similar to that in constant padding the Y2-axis label gets truncated.
