### ISSUE TITLE
Change background hash bar opacity percentage for accessibility contrast

### ISSUE THREAD

**Issue by laurenbock** [cerner/carbon-graphs#113]
Background hash bar at 30% opacity does not pass 3:1 contrast even with straight black. We need to update that percentage to allow for a darker gray, and/or change the color and the opacity as the color is locked down at the moment.

**Comment by laurenbock** [comment]
Proposal: 
![image](https://user-images.githubusercontent.com/57807487/68980042-e5e20200-07c4-11ea-84b0-e14d8eb9cddd.png)

**Comment by laurenbock** [comment]
@abhijit945 and I met - Either option is ok. We can make all background ones different opacity/colors.

**Comment by abhijit945** [comment]
Changes are only for Background Hash Bar and not other background bar entities within Gantt
