### ISSUE TITLE
Selections surround the icons on Gantt bug

### ISSUE THREAD

**Issue by laurenbock** [cerner/carbon-graphs#115]
Instead of just centering the selection, the selection should surround the icon clicked. This is what happens on implementation of gantt in MAR: 
![image](https://user-images.githubusercontent.com/57807487/69091058-1cab5880-0a0f-11ea-8dfc-b8f41859a16e.png)

**Comment by abhijit945** [comment]
Why is this a bug?

**Comment by laurenbock** [comment]
I am not sure if it is a bug or if it really is a feature request because the code is functioning as designed. It is aligning the selection in the center of the row but in reality it should surround the event that is clicked, wherever that is aligned in the row.

**Comment by abhijit945** [comment]
So this is an enhancement for selection indicator to conform to the shape of the icon?

**Comment by laurenbock** [comment]
Not just match the shape of the icon, but also the placement within the row. But I guess so... yes. If it encompasses the icon, it should align to wherever the icon is placed in the row. So maybe it is already covered by: https://github.com/cerner/carbon-graphs/issues/5 ?

**Comment by abhijit945** [comment]
If so then can we close this?

**Comment by laurenbock** [comment]
This is covered by #5 so I am closing.

**Comment by laurenbock** [comment]
Separating this as a separate issue to the selection shape.

**Comment by laurenbock** [comment]
Separating this as a separate issue to the selection shape.
