### ISSUE TITLE
Padding Top on Timeline changes the width of the timeline

### ISSUE THREAD

**Issue by dp21g** [cerner/carbon-graphs#117]
**Describe the bug**
When you add padding top value above 0 and all the other padding properties are 0. It seems to be changing the width of the timeline, thus causing our other components out of sync with it.

**To Reproduce**
see running example here:
https://codesandbox.io/s/nervous-hofstadter-g07l2

**Expected behavior**
Only the top padding should be applied, the width should remain the same.

**Screenshots**
![Screen Shot 2019-11-21 at 17 33 34 1](https://user-images.githubusercontent.com/6085036/69363343-44f1bc00-0c88-11ea-9842-da8543a6d392.png)

**Desktop (please complete the following information):**
-   OS: Mac
-   Browser: Chrome

**Comment by abhijit945** [comment]
@pranav300 Is this confirmed as a bug? Did we investigate why the shifting is happening?
