### ISSUE TITLE
Specific event line / Vertical dashed line

### ISSUE THREAD

**Issue by laurenbock** [cerner/carbon-graphs#119]
Create the ability to have dashed lines as a feature in Carbon similar to the date line concept already present. Allow for gray and dashed lines. Should overlay the content (highest z-index). 

I would suggest we use a solid color for these since the user can toggle them on/off via the Event Timeline. The date lines that already exist cannot be toggled so those are semi-transparent.

**Comment by abhijit945** [comment]
Maybe call this `eventline` to be consistently named like `dateline` ?

**Comment by abhijit945** [comment]
I think we can create a JIRA for this since this would need requirements. Maybe ask the consumers to populate the acceptance criteria as well.

**Comment by laurenbock** [comment]
Ok - should i just create that instead?

**Comment by laurenbock** [comment]
https://jira3.cerner.com/browse/CARBON-81 created!

**Comment by abhijit945** [comment]
I am going to close this since we are tracking this over at `CARBON-81`
