### ISSUE TITLE
Change non-hash background bars to include a border for accessibility

### ISSUE THREAD

**Issue by laurenbock** [cerner/carbon-graphs#123]
The current background bar design does not allow for high-enough contrast for background bars against the background of the gantt. The library goal of a background bar is to have an indication of a status (like total duration, expected duration, life of the order, etc.) but not be overpowering to the foreground bars or the primary information of duration (like effort length, dialysis duration, or medication administration duration). In order to create a visible foreground and background bar and events/actions on foreground bars, the background bar fill must remain relatively light, but I would suggest adding a border to it to pass contrast against the row background. This will allow for the foreground bar to pass against the background bar and the background bar border to pass against the row background. 

Example: 
![image](https://user-images.githubusercontent.com/57807487/70666182-c0b1a980-1c33-11ea-85ea-8fe9eec6ee12.png)

**Comment by abhijit945** [comment]
Do you want this border applicable for Bar Graphs? How does that stack up with accessibility?

**Comment by laurenbock** [comment]
No, this would just be for the background bars in gantt because they have opacity applied. Bars in bar graphs and foreground bars are solid so we are ok.

**Comment by abhijit945** [comment]
Ah gotcha, sounds good.

**Comment by abhijit945** [comment]
How much border do you like? 3px? 

3px

![image](https://user-images.githubusercontent.com/4908886/71281360-4cf25980-2323-11ea-82a9-8a5827f450fd.png)

2px

![image](https://user-images.githubusercontent.com/4908886/71281373-554a9480-2323-11ea-8c73-0eb03d8f17cb.png)

1px

![image](https://user-images.githubusercontent.com/4908886/71281394-5ed3fc80-2323-11ea-98ea-d34d8e437fc5.png)

**Comment by laurenbock** [comment]
I like 2px but I think we should actually use 1px because I want to make sure that when a user selects something that this border doesn't look too much like it is "selected". I'm afraid the 3px looks too emphasized. Just to check, the border is 100% opacity, but the fill is 30% opacity, right?

**Comment by abhijit945** [comment]
Correct

**Comment by laurenbock** [comment]
Let's do 1px. Thanks!
