### ISSUE TITLE
The legends are not properly displaying in the left with graph

### ISSUE THREAD

**Issue by NarasimhaShenoi** [cerner/carbon-graphs#129]
**Describe the bug**
Previously we were displaying the legends at the bottom of the graph. And the legends were displaying properly. Now when we tried to move the legends to left of the graph, we are facing the issue that the legends are not properly displaying with the graph. 

We have created the first graph with the div id legendContainer and set bindingLegendTo to the legendContainer. In another graph, we are using id as canvasLegendContainer and setting it to bindingLegendToGraph, which is in different file (class).
Finally, we are displaying these two in a single page display. 

Even though we are providing the legends in 2 separate divs, sometimes both the divs(with the legends) are coming under one graph. And nothing is being displayed for the second graph.

**To Reproduce**

1. Go to 'https://github.cerner.com/Assessments/assessments-graph-js'.
2. Go to 'advgraph-1152' branch.
3. Do 'npm install' to build the project.
4. Do 'npm start' to run the project.

**Expected behavior**
When we run the application, initially the legends will be appearing properly with the graph. And the legends will be appearing in the separate divs. When we reload the graph or go to tests tab and reload back to components tab in dev site, the legends are not appearing properly with the graph. The legends are appearing in the same div.

**Screenshots**
<img width="1440" alt="Screen Shot 2019-12-20 at 6 45 22 PM" src="https://user-images.githubusercontent.com/53594676/71257229-2f3fe700-2359-11ea-9da4-c214adb731ee.png">
<img width="1440" alt="Screen Shot 2019-12-20 at 6 45 35 PM" src="https://user-images.githubusercontent.com/53594676/71257230-2f3fe700-2359-11ea-8f83-aad36445c330.png">
<img width="1440" alt="Screen Shot 2019-12-20 at 6 45 57 PM" src="https://user-images.githubusercontent.com/53594676/71257231-2f3fe700-2359-11ea-8cee-1547ccbb1f02.png">

**Desktop (please complete the following information):**
-   Browser : Chrome

**Additional context**

**Comment by abhijit945** [comment]
I tried it in a sandbox and it is working fine. 

![image](https://user-images.githubusercontent.com/4908886/71263212-14dd1d80-2307-11ea-8736-339c6547bb6d.png)

You can see the source here: https://codesandbox.io/s/trusting-clarke-91qkx?fontsize=14&hidenavigation=1&theme=dark

**Comment by abhijit945** [comment]
Closing this as it is working as expected.
