### ISSUE TITLE
Toggling of Non-Contiguous Line Legend Adds a Data Point 

### ISSUE THREAD

**Issue by erinplourde** [cerner/carbon-graphs#161]
When the legend item is toggled off and then on again for a non-contiguous line, a random point will appear at the bottom of the graph. 

When the legend item is toggled back on, no new points should be added to the graph 

<img width="801" alt="Screen Shot 2020-02-04 at 11 44 34 AM" src="https://user-images.githubusercontent.com/52933964/73963477-fabac700-48d5-11ea-807f-d432f44666bb.png">

**Comment by Prashant-Kamboj** [comment]
We have to handle the y = null case in this inside the clickHandler

` const point = canvasSVG
        .selectAll(`.${styles.point}[aria-describedby="${item.key}"]`)
        .attr("aria-hidden", legendSelected);

point.each(function(node) {
        if (node.y !== null) {
            d3.select(this).attr("aria-hidden", legendSelected);
        } else {
            d3.select(this).attr("aria-hidden", true);
        }
`

**Comment by pranav300** [comment]
Is it required to render the data point with y value as null in the DOM?

cc / @abhijit945

**Comment by abhijit945** [comment]
@pranav300 Yeah I agree, we shouldnt render the data point in the first place. 
@Prashant-Kamboj Can you think of doing the same for bubble? I dont think we would even need to do the processing in `clickHandler` if there is no data point in the dom

**Comment by Prashant-Kamboj** [comment]
Yes, I will handle in that way I will not add any bubble point in the DOM if the value is null.
