### ISSUE TITLE
Unable to remove decimal points when dimensions of graph is increased.

### ISSUE THREAD

**Issue by tensed** [cerner/carbon-graphs#178]
**Describe the bug**
When the dimensions of the graph is increased, the Y-Axis and the Y2-Axis values ends up getting converted to decimal points and when I tried to use the format option in the tick axis property, I'm getting an error **"t.numberFormat is not a function"**.

**Link to CodeSandbox**

Replicated the behavior here [ISSUE](https://codesandbox.io/s/youthful-newton-njfnt) 

**Expected behavior**
The values of the Y-Axes to be integers rather than it getting converted to decimal points.

**Screenshots**
When the height of the dimension property is set to 400.
<img width="678" alt="Screenshot 2020-03-11 at 3 41 46 PM" src="https://user-images.githubusercontent.com/41514402/76406204-5681df80-63af-11ea-8b7b-54c650e1e9cc.png">

When the height of the dimension property is set to 600.
<img width="675" alt="Screenshot 2020-03-11 at 3 41 30 PM" src="https://user-images.githubusercontent.com/41514402/76406156-45d16980-63af-11ea-9389-7587d9041874.png">

**Desktop (please complete the following information):**

-   OS: MacOS
-   Browser : Chrome

**Additional context**
The number formatting seemed to be causing the issue.

**Comment by pranav300** [comment]
@tensed
What I am seeing in the sandbox that you are using carbon-graphs v1.20.1. 
Can you try upgrading to v2.0.1? As when I tried with it, I was able to remove the decimals.

**Comment by tensed** [comment]
@pranav300 It worked! Thank you for your response.
