### ISSUE TITLE
Red Criticality Border Remains on When Toggled Off

### ISSUE THREAD

**Issue by erinplourde** [cerner/carbon-graphs#192]
When a legend item is toggled off and the user hovers over the legend item, the red criticality border appears on the screen. 

This should be changed so that the red border is completely toggled off with the rest of the line. When the user toggles off the legend item, the entire line should disappear. When the user toggles off the legend item, the entire line and criticality indicators should disappear (even upon hover of the legend item).

<img width="1005" alt="Screen Shot 2020-03-30 at 9 30 23 AM" src="https://user-images.githubusercontent.com/52933964/77924323-2bc9cf00-7269-11ea-849a-a782c198bb10.png">

**Comment by pranav300** [comment]
@erinplourde 
Maybe this is intended to work like this.
If a user toggles data off let's say Blood Pressure, then while hovering over the legend, I think we must show critical points. So, even when the data is not visible they can check for criticality just by hovering over the legend.

cc / @mraplumb @swatikode @ShettyAkarsh

**Comment by mjhenkes** [comment]
@pranav300 We should not show hovers for disabled data points, This is a bug.
