### ISSUE TITLE
Fix Graph Padding

### ISSUE THREAD

**Issue by erinplourde** [cerner/carbon-graphs#207]
UX would like to update the padding around the graphs and legend items. 

Our recommendation is that, for line graphs, there would be 10 px of padding above and below the graph and 5 px of padding above and below each legend item. (More investigation will be needed to provide a recommendation on padding for other graph types).
<img width="750" alt="Screen Shot 2020-04-28 at 3 55 43 PM" src="https://user-images.githubusercontent.com/52933964/80536899-bab13080-8968-11ea-84f6-b0c09179ce4c.png">

**Comment by jananigunas** [comment]
I have started looking into this issue. I have a query regarding the setCanvasHeight function. I wanted to understand why we are adding padding top, padding bottom and x axis label height together and multiplying it by 2 [here](https://github.com/cerner/carbon-graphs/blob/master/src/main/js/controls/Graph/Graph.js#L74-L77). 
@ryanthemanuel , @mraplumb Can you please let me know the reason behind this logic?

**Comment by pranav300** [comment]
>why we are adding padding top, padding bottom and x axis label height together and multiplying it by 2

For the padding-top, padding-bottom, and x-axis label height as they are part of the graph canvas. And we multiply them by 2 so that we can get enough space for the legend or otherwise it will be overlapping the x-axis label.

**Comment by JananiGunasekaran** [comment]
@ryanthemanuel, @mraplumb I have raised PR related to this issue : https://github.com/cerner/carbon-graphs/pull/213. Please review.
