### ISSUE TITLE
Grid Lines : Center the Grid Lines instead of starting precisely at the input position.

### ISSUE THREAD

**Issue by abhijit945** [cerner/carbon-graphs#21]
**Is your feature request related to a problem? Please describe.**
* Yes, currently the grid lines get drawn precisely at the scaled position. We want the ability to center this.

Ex., Dateline starts at date X. The grid line starts to draw at Position X and ```3px``` towards right. This feature should make ```1.5px``` towards left and ```1.5 px``` towards right. Making it look like its centered.

**Describe the solution you'd like**
* Is it possible, for Snapping the dateline at position X and center it with CSS, when we have a property for ```snapping```

**ScreenShots**

![image](https://user-images.githubusercontent.com/4908886/61050862-9b332200-a3ad-11e9-86d6-582d479a24f0.png)

Edit: 

* Instead of making it a passive-change, can we make this a non-passive change and get rid of a new property ```snapping``` and centering it based on that. Not sure, if it would affect other consumers.

**Comment by AshishMotanamGurunadham** [comment]
Not an issue any more. 
![image](https://user-images.githubusercontent.com/63670637/91192405-80a82f00-e6bb-11ea-8a33-14bff0bc23f7.png)
