### ISSUE TITLE
Paired Result Graph: Clicking legend of one graph affecting the graph another Graph

### ISSUE THREAD

**Issue by SharathAlur** [cerner/carbon-graphs#212]
**Describe the bug**
Clicking the legend of one paired result in a graph affects another paired result present in the different graphs.
Looks like the issue is introduced in version 1.19.2. The previous version 1.19.1 is working fine.

**Link to CodeSandbox**

Use [this](https://codesandbox.io/s/autumn-dust-8vxc1?file=/src/data.js) template to reproduce the behavior. 

**Expected behavior**

**Screenshots**
<img width="630" alt="Screenshot 2020-05-19 at 1 29 07 PM" src="https://user-images.githubusercontent.com/22268936/82300662-c6769c80-99d4-11ea-8c6d-15de66a771d1.png">

**Desktop (please complete the following information):**

-   OS: iOS
-   Browser: chrome

**Additional context**
Looks like the issue is introduced in version [1.19.2](https://github.com/cerner/carbon-graphs/releases/tag/v1.19.2). The previous version [1.19.1](https://github.com/cerner/carbon-graphs/releases/tag/v1.19.1) is working fine.

**Comment by JananiGunasekaran** [comment]
@ryanthemanuel, @mraplumb I have raised PR related to this issue : https://github.com/cerner/carbon-graphs/pull/224. Please review.
