### ISSUE TITLE
Padding property doesn't take space into account when hasCustomPadding property is true

### ISSUE THREAD

**Issue by abhijit945** [cerner/carbon-graphs#22]
**Describe the bug**
For bar graph, when the padding prop is provided(no matter what the value is), the Y-axis label becomes closer to Y-axis. Looks like the default white space between label and Y-axis is gone once you provided a customized padding prop.

When no padding props provided by the consumer: 
![image](https://user-images.githubusercontent.com/4908886/61050732-4d1e1e80-a3ad-11e9-899d-2cb6db389c26.png)

When provided costomized padding as `{left: 30, right: 50}`:
![image](https://user-images.githubusercontent.com/4908886/61050747-50b1a580-a3ad-11e9-9505-da0e131e01bf.png)

**To Reproduce**

1. provide the padding props in code like 
```
    axisData.padding = {
        right: 50
    };
```
or 
```
    axisData.padding = {
        left: 30,
        right: 50
    };
```

**Expected behavior**
Expected to keep the white space between Y-axis label and Y-axis when padding prop is provided.

![image](https://user-images.githubusercontent.com/4908886/61050757-55765980-a3ad-11e9-82b6-d41607ffcf9b.png)

**Screenshots**
see above.

**Desktop (please complete the following information):**
-   OS: mac OS
-   Browser: Chrome

**Additional context**

**Comment by jeffmerten** [comment]
We're seeing an issue where the padding right attribute not being honored for the timeline. Not sure if this padding issue will include the resolution for that or if it would be scoped in another fix.

**Comment by Santosh086** [comment]
@abhijit945 / @ryanthemanuel - Any thoughts for this issue on when it will be fixed?

**Comment by Santosh086** [comment]
@abhijit945 / @ryanthemanuel - Any thoughts on this issue when it will be fixed?

**Comment by abhijit945** [comment]
@pranav300 is working on the changes as of this moment. We are trying to figure out the conditions we are trying to solve along with the best possible method to achieve it passively. Since this is core to the functioning of each graph we are being very cautious. 

It is our top priority as of now. Any progress will be reflected as part of PR https://github.com/cerner/carbon-graphs/pull/83.
