### ISSUE TITLE
Eventlines on timeline api

### ISSUE THREAD

**Issue by leducquan** [cerner/carbon-graphs#225]
Create the ability to have eventlines (dashed-lines) appear for the timeline api , under the svg icons.

We currently have an implementation of the carbon timeline and require the eventlines to also be ported to the timeline api.

![image](https://user-images.githubusercontent.com/19377430/83393521-d5a31480-a3ee-11ea-8ecc-11d579d3ed8f.png)

Thoughts on having this as a feature of carbon?

**Comment by erinplourde** [comment]
Event lines should be added to the event timeline. This will help aid users in connecting the event timeline above the Stella timeline to the event lines in the components below. 

We want to allow for 15 px of the line to show below the plotted symbols. 

![image](https://user-images.githubusercontent.com/52933964/92135859-ec338000-edd0-11ea-84c1-721cc3407d3b.png)

**Comment by mjhenkes** [comment]
no longer needed
