### ISSUE TITLE
Allow consumers to use a whole number instead of decimal 

### ISSUE THREAD

**Issue by erinplourde** [cerner/carbon-graphs#234]
When a Y-axis range contains decimals, carbon always displays all numbers in that range with a decimal. 
![MicrosoftTeams-image (33)](https://user-images.githubusercontent.com/52933964/84037561-61272300-a964-11ea-95ce-5fbd32c0c94e.png)

Give consumers the ability to display whole numbers and decimals in a range. This is to help users distinguish between a change to a new whole number within that range. 
![image](https://user-images.githubusercontent.com/52933964/84037953-e90d2d00-a964-11ea-88e6-409e86ea8051.png)

**Comment by JananiGunasekaran** [comment]
@ryanthemanuel @mraplumb I have started looking into this issue. Can you please let me know if we should introduce a new prop to allow consumers to toggle between either "suppress trailing zeros in a range" or "allow the trailing zeros"? 

Or without introducing a new prop, should we be suppressing all trailing zeros by default for a range?

Please let me know about this. Thanks!

**Comment by JananiGunasekaran** [comment]
@ryanthemanuel @mraplumb I have raised PR related to this issue : https://github.com/cerner/carbon-graphs/pull/248. Please review.

**Comment by chrismichalewicz** [comment]
@JananiGunasekaran   I have created [CARBON-147](https://jira3.cerner.com/browse/CARBON-147) to track requirements,testing,tracing,etc. I have made you the owner of it.
