### ISSUE TITLE
Chore: Update the husky hooks and .releaserc tags

### ISSUE THREAD

**Issue by Veera81** [cerner/carbon-graphs#237]
- We will update the husky hooks in the package.json
     1. Remove the `git add -u` from the `pre-commit` hook and add `npm run lint` to the `pre-commit` 
          hook
     2. Add the `npm run test` command to `pre-push` hook
-  Remove the `Doc`, `Chore` and `Build` from the release tags as we don't have to release the carbon 
    graphs if we have any of those tags
     1. **Chore**: Changes to the build process or auxiliary tools and libraries such as documentation 
         generation
     2. **Docs** - changes to documentation only.
     3. **Build** - changes to build process only.
- Update the documentation for the commit message formats in the carbon repo

**Comment by sdadn** [comment]
I believe 1.ii is to add `npm run test` to `pre-push` hook.
