### ISSUE TITLE
Data points are hidden behind other Line Plots

### ISSUE THREAD

**Issue by hackawesome** [cerner/carbon-graphs#240]
**Describe the bug**
The data points are hidden behind the line graphs. I tried with different reordering of load Content but still the line plots overshadows the data points.

**Link to CodeSandbox**
 https://github.cerner.com/aeon-womenshealth/fundal-height-js/blob/b4ab9940ec03a3b431f63350b6b3a4bbcbc3282a/src/fundal-height/utils/DataHelpers.js#L267

**Expected behavior**
The data points should load in front of other line plots or there should be preference of the top layer.

**Screenshots**
Whole Component
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/66961568/84677665-ac38cb80-af4c-11ea-8b15-33dce814a341.png">

Zoom on the issue:
<img width="237" alt="image" src="https://user-images.githubusercontent.com/66961568/84677737-c8d50380-af4c-11ea-8bd9-820133e9580e.png">

**Comment by AshishMotanamGurunadham** [comment]
can you provide the exact link of where you are loading content into the graph?

**Comment by hackawesome** [comment]
@AshishMotanamGurunadham 
We have created a reusable top layer component called preganncy base graph js
https://github.cerner.com/aeon-womenshealth/pregnancy-base-graph-js/blob/cbcdfbe530bf1de51d4185db464f94fda3d18a8b/src/pregnancy-base-graph/components/PregnancyBaseGraphBuilder.jsx#L41 
We send the line plot object as a prop & the pregnancy base graph renders it

Consuming end of Pregnancy Base Graph: 
https://github.cerner.com/aeon-womenshealth/fundal-height-js/blob/b4ab9940ec03a3b431f63350b6b3a4bbcbc3282a/src/fundal-height/components/FundalHeightView.jsx#L168

**Comment by AshishMotanamGurunadham** [comment]
@hackawesome looks like you are loading line content first. Can you please try loading spline first and then followed by line into the graph?

**Comment by hackawesome** [comment]
@AshishMotanamGurunadham  That worked for me. I have changed the orders for line content. Thanks for the help
