### ISSUE TITLE
Define X Axis values for Regions as well as Y Axis

### ISSUE THREAD

**Issue by davidhunt88** [cerner/carbon-graphs#244]
**Is your feature request related to a problem? Please describe.**
We are replicating the functionality we have on our MPage in Carbon in order to upgrade the MPage to modern libraries. Currently we are missing a key piece of functionality that is one of the key items of our MPage.

**Describe the solution you'd like**
We need to display regions on graphs that can change during the graph X Axis range. This is to replicate functionality we achieve using an old library called JQPlot. We would like to be able to specify the X Axis in the same way as we do the Y Axis and the region would draw on that X Axis range for the Y Axis range specified.

**Describe alternatives you've considered**
Only alternative is to continue using our existing library which is out of date and heavily customised so is not easily updated to latest version available.

**Additional context**
Here is an example of how it looks on our old existing MPage using the old library
![Screen Shot 2020-06-22 at 5 32 53 pm](https://user-images.githubusercontent.com/36438506/85260725-7b0d4d80-b4ae-11ea-9872-cfa130793efd.png)

**Comment by davidhunt88** [comment]
Is it possible to get a timeline for this being looked at please. We need to have a rough date so that we can communicate this on the project

**Comment by mraplumb** [comment]
@davidhunt88 there is a current project to enhance reference ranges (regions) allowing them to be plotted by value instead of for the entire data set.  This project is mainly to account for reference ranges that change over time but might apply to what you are needing.  [This PR](https://github.com/cerner/carbon-graphs/pull/258) has some screenshot examples.  Can you take a look to see if that might align with what you are needing?

**Comment by davidhunt88** [comment]
@mraplumb the only issue I have looking at the screenshots and the code is that it requires a value to exist and then the range is only applicable to that value. I need to be able to specify the region on the graph without having a value in place in that specific position. My screenshot above is where the region is specified after the value is entered and is not applicable to that value. I was hoping I could have something like the below in the region section of the options for the graph as an example so there is no reliance on the need for a value on the graph:

regions: [
    {
      x:{
        start: "2020-06-18T06:00:00.000Z"
        end: "2020-06-18T08:00:00.000Z"
      },
      y:{
      start: 200,
      end: 250,
      },
      color: "#ff7d00"
    }
  ]

**Comment by mraplumb** [comment]
@davidhunt88 we discussed this in a meeting today and wanted to get more information around your request.  

- Am interpreting your request correctly that you want to display a Carbon region across the graph regardless if data is charted and be able to vary the vertical range of the region based on stop and end points along the X-axis?
- Can you describe the use case of when you would need to display a region/reference range when there is no data associated? 
 - Are the colored sections in the graph image you provided used to convey reference information about the data in the graph or something different? 
 - What benefit does the functionality provide?
 - What do your end users do with this information?

**Comment by davidhunt88** [comment]
@mraplumb please see my responses to your questions below. If anything doesn't make sense or you need more information then please let me know:

•	In this case, I would display the regions across the graph only if the graph date range has at least one data value charted. As an example, I could have a graph running from 12:00pm on the 2nd July to 12:00pm on the 3rd July. On the graph I have a data value displaying at 08:00am on the 3rd July. The region is the same across the graph till it gets to 10:00am on the 3rd July when it changes. There is no data value to associate the change to.

•	The reason for displaying region with no data associated to it is because clinicians would change the regions for certain patients when required to alert to a patient deteriorating sooner. They would do this without a value associated to the change and then future values logged would fall into the range and display correctly. It is also used for historic purposes to see when the range was different, particularly when a patients chart type changes.

•	The coloured sections in the graph image provided are used to convey the abnormal ranges for a patients observation. If a value enters those ranges then an alert is triggered to let the user know the patient is deteriorating. This can vary from a warning (blue/yellow) to an urgent MET call that needs attention immediately(red).

•	The benefit of this change is that regions are clearly aligned to the graph and not individual values. This would improve the visibility on graphs where there are no values for part of the date range on the graph. It is also something that would help adoption of advanced graphing in the future for our clients here in Australia as part of the reason behind the creation of our MPage was a lack of a Cerner IP solution for graphing that catered to this scenario.

•	The information is used to trend a patients observations to ascertain whether or not the patient is deteriorating. The values shown on the graph could be increasing or decreasing towards a region that would result in an alert. By seeing this, the clinician can take action before the patient deteriorates to a point where they are harmed. Also, the clinician altering the regions allows for staff to get alerted when the clinician is not available and can take action straight away
