### ISSUE TITLE
Big gap when x axis values starts/ends with an odd integer

### ISSUE THREAD

**Issue by hackawesome** [cerner/carbon-graphs#246]
**Describe the bug**
I tried implementing a graph where we want to start from 23 weeks to 42 weeks but we are getting a big gap before our ticks.
My ticks are from 24 to 42 but wanted a headroom for the line plots, so I tried to start the graph from 23 but it shows a large gap

**Link to CodeSandbox**
Project link: https://github.cerner.com/aeon-womenshealth/fundal-height-js
Helper file: https://github.cerner.com/aeon-womenshealth/fundal-height-js/blob/b4ab9940ec03a3b431f63350b6b3a4bbcbc3282a/src/fundal-height/utils/DataHelpers.js#L153
Constants file: https://github.cerner.com/aeon-womenshealth/fundal-height-js/blob/b4ab9940ec03a3b431f63350b6b3a4bbcbc3282a/src/fundal-height/data/swedenGraphData.json#L2

**Expected behavior**
Graph should start from any values with provided ticks

**Screenshots**
Case 1: If I try to start graph from 23 to 42 on x axis & provide ticks in 1 increment
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/66961568/85431500-43320300-b59f-11ea-86b6-628df4cb5f8f.png">

Case 2: If I try to start the graph from 23 to 42 on x axis & provide ticks starting from 24. There is a sizeable gap
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/66961568/85431143-c0a94380-b59e-11ea-8e84-6f734eea2214.png">

Case 3: If I try to give 23 to 43 for x axis values & ticks in 1 increment. Gap increased on both left and right end
<img width="1672" alt="image" src="https://user-images.githubusercontent.com/66961568/85431248-e59db680-b59e-11ea-95f6-751de3f13e4a.png">

**Comment by sdadn** [comment]
@hackawesome Thanks for your input. I investigated the issue. By default, Carbon rounds off numbers to the nearest multiple of 2, 5 or 10 for cleaner values. The “gap” you’re seeing is basically the lower limit being rounded down to 22 to accommodate 23, and the upper limit gets extended to 44. 

<img width="870" alt="Screen Shot 2020-06-23 at 2 51 55 PM" src="https://user-images.githubusercontent.com/38024451/85453253-4efed480-b561-11ea-8ad1-ca8e3c1210cc.png">

<img width="869" alt="Screen Shot 2020-06-23 at 2 52 16 PM" src="https://user-images.githubusercontent.com/38024451/85453270-53c38880-b561-11ea-8824-4dd6f7ac3ad1.png">

Similarly, if I set my range from 104 to 148, the limits get rounded to 100 and 150, which are multiples of 10.

<img width="858" alt="Screen Shot 2020-06-23 at 3 02 11 PM" src="https://user-images.githubusercontent.com/38024451/85454790-e1ec3e80-b562-11ea-9738-5a92311f2422.png">

<img width="858" alt="Screen Shot 2020-06-23 at 3 02 40 PM" src="https://user-images.githubusercontent.com/38024451/85454703-cf720500-b562-11ea-8aa2-c71c5d02edc1.png">

So, this isn’t really a bug, just Carbon's default behavior with axis values for cleaner labels. There is a property, `allowCallibration`, that can be used to bypass this behavior for the Y-axis, but we can definitely look at extending that functionality to the X-axis for a future release. In the meantime, I would suggest using even numbers for your x-axis limits to make the gap look less obvious.

**Comment by hackawesome** [comment]
Alright Thank you @sdadn 
Is there any feature or fix in the backlog to allow callibration

**Comment by sdadn** [comment]
@hackawesome Yes, I just created the new issue for this feature.

**Comment by sdadn** [comment]
This issue has now moved to:

https://github.com/cerner/carbon-graphs/issues/250
