### ISSUE TITLE
Shapes get cut off when values are mapped at limits (Ticks alignment breaks if we use padDomain/rangeRounding)

### ISSUE THREAD

**Issue by tensed** [cerner/carbon-graphs#270]
**Describe the bug**
Currently using carbon@2.8.1 and the ticks issue was sorted after the new fix was added.

The values at the edges are getting cut off if we add them at the extreme limits of the graphs and ideally padDomain and rangeRounding would fix this issue. 

But if we try to use them, the y2-axis does not seem to align with the y-axis ticks and the y2-axis ends up considering the rangeRounding and padDomain limits(the extra tick) as the start and end of the graph and do not align with each other.

Tried replicating this issue in sandbox but the behavior of the sandbox is slightly different from the one which I've implemented even when all the graph properties are the same. 

**The ticks are not aligning in the sandbox. (Carbon@2.8.1)**
<img width="556" alt="Screenshot 2020-07-10 at 1 27 34 PM" src="https://user-images.githubusercontent.com/41514402/87130866-33a9fe00-c2b1-11ea-8dab-216215c2d197.png">

**When padDomain and rangeRounding is true (Carbon@2.8.1) (Behaviors do not match when using sandbox and using the package in local)**
<img width="556" alt="Screenshot 2020-07-10 at 1 59 11 PM" src="https://user-images.githubusercontent.com/41514402/87134016-b8971680-c2b5-11ea-8a62-e370270aeec6.png">

**Replicated the same in local and the ticks are aligned (Carbon@2.8.1)** 
<img width="1221" alt="Screenshot 2020-07-10 at 1 21 30 PM" src="https://user-images.githubusercontent.com/41514402/87130978-5dfbbb80-c2b1-11ea-90d1-0f9f130a6939.png">

**When padDomain is true for both y and y2-axis (The shapes are visible but the ticks aren't aligned) (Carbon@2.8.1)** 
<img width="1169" alt="Screenshot 2020-07-10 at 1 47 44 PM" src="https://user-images.githubusercontent.com/41514402/87132827-0ca0fb80-c2b4-11ea-87e3-9a3928ba2b5d.png">

**When padDomain and rangeRounding is true for both y and y2-axis (Carbon@2.8.1)**
<img width="1177" alt="Screenshot 2020-07-10 at 1 52 26 PM" src="https://user-images.githubusercontent.com/41514402/87133365-d748dd80-c2b4-11ea-9546-3e628349ebea.png">

**When we removed the y2-axis ticks value (defined for -5 and 5) as well as y-axis ticks value (defined for 0 and 10) and the padDomain and rangeRounding is true**
<img width="1179" alt="Screenshot 2020-07-10 at 1 55 11 PM" src="https://user-images.githubusercontent.com/41514402/87133508-10814d80-c2b5-11ea-8c3f-239598018c9e.png">

**Both Sandbox and Local are using the same properties** 
<img width="515" alt="Screenshot 2020-07-10 at 1 23 38 PM" src="https://user-images.githubusercontent.com/41514402/87131010-681dba00-c2b1-11ea-97d2-5cdbf424a000.png">

**Link to CodeSandbox**
[SandBoxCode](https://codesandbox.io/s/dazzling-chandrasekhar-dnec8?file=/src/data.js)

**Expected behavior**
Ideally, when the padDomain and rangeRounding is true as well as the ticks are defined, the y2-axis and y-axis ticks should be aligned to each other.
Was able to replicate this in 2.4.0 where padDomain and rangeRounding are true, but the ticks stop aligning after we load another dataset to the y2-axis.(This automatically aligns in the latest 2.8.1 version due to the ticks fix in v2.6.1)   

**When only two dataset with **padDomain** and **rangeRounding** as true in CARBON V2.4.0** 
<img width="1198" alt="Screenshot 2020-07-10 at 1 32 54 PM" src="https://user-images.githubusercontent.com/41514402/87131565-35c08c80-c2b2-11ea-989a-deb89cc7b90e.png">

**Behavior when three or more datasets are loaded in CARBON V2.4.0** 
<img width="1161" alt="Screenshot 2020-07-10 at 1 36 09 PM" src="https://user-images.githubusercontent.com/41514402/87131715-6f919300-c2b2-11ea-9aab-8a70be8d2734.png">

**Desktop (please complete the following information):**

-   OS: MacOS Mojave
-   Browser : Chrome, Firefox

**Additional context**
- In the latest version only the padDomain and rangeRounding for y2-axis seems to be breaking the alignment of the ticks. 
- We can't give a permanent ticksCount to the graph as the y2-axis ranges are dynamic and changes according to how its configured. 
In this case its (-5 and 5) and (0 and 5) where they're (*lower limit* and *upper limit*) respectively.
- Did try setting the allowCalibration properties as well, it didn't seem to make much of a difference and the alignment remained the same as shown in the screenshots

**Comment by sdadn** [comment]
Hi @tensed , I investigated this issue. So far, it does not seem like a bug in the code logic. A few things to note:

1. The ticks are not really misaligned; they are just in different positions in different scales. The scale gets updated to give padding to extreme data-points, resulting in the ticks position changing.

2. You’re using custom ticks, so you need to use appropriate values and ranges for both axes for alignment. To obtain alignment, yo need to make sure both ranges are divided into the same number of intervals. Logically, you can’t divide two things into a different number of parts and expect them to align. They both need to to have the same divisions. 

So far, i’ve been unable the replicate the issue without using custom values. I used a ticksCount value of 7, and here are my results:

`ticksCount: 7`

<img width="939" alt="image" src="https://user-images.githubusercontent.com/38024451/88571892-f4471580-d003-11ea-92a5-90cbfc364080.png">

<img width="916" alt="image" src="https://user-images.githubusercontent.com/38024451/88571925-fd37e700-d003-11ea-8295-0a15a3cf61dc.png">

<img width="913" alt="image" src="https://user-images.githubusercontent.com/38024451/88571950-0759e580-d004-11ea-8247-902a020d6db1.png">

<img width="912" alt="image" src="https://user-images.githubusercontent.com/38024451/88571988-10e34d80-d004-11ea-9002-d7f7404291f1.png">
