### ISSUE TITLE
Remove shape in y-axis when showShapes in data is set to false.

### ISSUE THREAD

**Issue by AshishMotanamGurunadham** [cerner/carbon-graphs#273]
**Describe the bug**
- When y2 axis is present in graph, shapes are displaying on line graph y-axis even though we set showShapes in data to false.
- When y2 axis is present in graph, shapes are displaying on line graph y-axis even though we did not provide any values for the content in graph.
 
**Link to CodeSandbox**

https://codesandbox.io/s/happy-meninsky-u4nie?file=/src/data.js
https://codesandbox.io/s/objective-bird-qw5ll?file=/src/data.js

**Expected behavior**
When showShapes is set to false in data, we should not display any shape on the y-axis or y2-axis with respect to that particular data content.

**Screenshots**

![image](https://user-images.githubusercontent.com/63670637/87608656-1f596d00-c6c6-11ea-8a5e-b1190831b8e2.png)

![image](https://user-images.githubusercontent.com/63670637/87608762-592a7380-c6c6-11ea-97da-3f27e539071f.png)

**Comment by AshishMotanamGurunadham** [comment]
This is my solution for the issue, i am planning to replace shape with line(when showShapes is set to false) as shown below. 

@mjhenkes @jeremyfuksa @erinplourde please let me know your thoughts on this solution so that i can move on and fix the issue.  

![image](https://user-images.githubusercontent.com/63670637/91884320-74881880-ec4b-11ea-92c7-52f27eaf4b1e.png)

![image](https://user-images.githubusercontent.com/63670637/91884893-7acac480-ec4c-11ea-9e4c-9e617bb54d7e.png)

![image](https://user-images.githubusercontent.com/63670637/91884752-3e976400-ec4c-11ea-9c30-7e72a1c96c61.png)

![image](https://user-images.githubusercontent.com/63670637/91886086-70a9c580-ec4e-11ea-9b1c-e597517c7266.png)

**Comment by erinplourde** [comment]
@AshishMotanamGurunadham  I agree that the line should display instead of the symbol. Are able to ensure that the entire line pattern would show?
