### ISSUE TITLE
Labels should update with reflow

### ISSUE THREAD

**Issue by erinplourde** [cerner/carbon-graphs#277]
With the addition of reflow - the axis labels should update to accurately represent what is being displayed in the legend. If an item is removed from the legend (due to there being no data in the shown timeframe), that item should also be removed from the axis label. 

This will ensure consistency between the legend and the labels. This will help minimize user confusion - the user could believe something is wrong with the graph if the item appears in the axis label but not in the legend. 

Current: 
- Item is removed from the legend but remains in the axis label 
<img width="605" alt="Screen Shot 2020-07-23 at 1 42 41 PM" src="https://user-images.githubusercontent.com/52933964/88325272-7ecd0380-ccea-11ea-848e-ea2b9aac7287.png">

Proposed: 
-Item is removed from both the legend and axis label 
<img width="597" alt="Screen Shot 2020-07-23 at 1 42 57 PM" src="https://user-images.githubusercontent.com/52933964/88325319-90161000-ccea-11ea-9141-0af88af18e11.png">

**Comment by Veera81** [comment]
@NarasimhaShenoi Can you work on this as discussed since this defect fix will be required as a priority to your team

**Comment by NarasimhaShenoi** [comment]
@Veera81 Thank you for reassigning. Also, Let me know if any Jira is needed to create for this issue?

**Comment by NarasimhaShenoi** [comment]
@ryanthemanuel  @Veera81  @mraplumb  I have raised the pull request #290 for this? Please review
