### ISSUE TITLE
Remove symbols with data set is removed from legend. 

### ISSUE THREAD

**Issue by erinplourde** [cerner/carbon-graphs#286]
Symbols are not being removed from the y-axis label when they are being removed from the legend due to reflow. If a data set has no data in the presented timeframe and is removed from the legend, the symbol should also be removed from the y-axis label. This will help eliminate some confusion for the user. 

What is happening: 
<img width="841" alt="Screen Shot 2020-08-03 at 7 32 53 AM" src="https://user-images.githubusercontent.com/52933964/89182552-8e0a4780-d55b-11ea-96e8-921bfd00c8d7.png">

What should happen: 
<img width="800" alt="Screen Shot 2020-08-03 at 7 33 12 AM" src="https://user-images.githubusercontent.com/52933964/89182576-982c4600-d55b-11ea-8cb6-52dfdffdb099.png">

**Comment by sdadn** [comment]
@NarasimhaShenoi can you look at this since this is related to reflow?

**Comment by NarasimhaShenoi** [comment]
@sdadn  Sure, I will pick this up. Can you please assign this issue to me

**Comment by mraplumb** [comment]
@NarasimhaShenoi have you been able to make any progress on this bug or have any estimate when the update might be made?

**Comment by NarasimhaShenoi** [comment]
@mraplumb I have not started looking into this issue till now. I am working on other priority issues of our team.
