### ISSUE TITLE
Unverified Data Treatment

### ISSUE THREAD

**Issue by abhijit945** [cerner/carbon-graphs#29]
Create hollow shapes for unverified data points and connect them using a dotted line. 

![image](https://user-images.githubusercontent.com/4908886/61050571-ed277800-a3ac-11e9-96b3-058d96173bfe.png)

TBD - how hollow looks for critical values and dot frequency on line. 
UX is currently trying to work out the design on how the criticality indicator for unverified/outside record indicator and dot frequency.

**Comment by laurunning** [comment]
@abhijit945 - is the criticality a stroke built as a part of the shape or do we need separate svg assets?

**Comment by laurunning** [comment]
For reference, design standard post regarding unverified and unauthorized data: https://wiki.cerner.com/display/UserExperience/Standard+Graphs#StandardGraphs-LineGraph

**Comment by abhijit945** [comment]
For normal datapoints, the criticality indicator (white and red shapes) are just the regular shapes with respective fills stacked on top of each other.

**Comment by laurunning** [comment]
Ok. Do we need separate icons for the unverified data shapes? Or are those built like the critical ones?

**Comment by abhijit945** [comment]
It would be ideal if we were to get separate icons for Unverified data points. 
For unverified critical, do you have an example of how the data points would look like when critical? Would the border be black always or change based on the color scheme?

**Comment by erinplourde** [comment]
Here is that screenshot with all of the critical unverified icons
<img width="595" alt="Screen Shot 2019-07-19 at 11 15 01 AM" src="https://user-images.githubusercontent.com/52933964/61549787-8b9f8300-aa16-11e9-8a12-7e044fd67d69.png">

**Comment by laurunning** [comment]
@abhijit945 - we need to connect these points using a dashed line - is that complete?
