### ISSUE TITLE
Paired Result - Multiple Regions

### ISSUE THREAD

**Issue by abhijit945** [cerner/carbon-graphs#3]
When all but one data set is toggled off from the legend (note: a data set can contain paired values), the region(s) should appear face up

**Actual**

![image](https://user-images.githubusercontent.com/4908886/61313689-9234bd00-a7c0-11e9-96b0-ee1b4db87ca3.png)

**Expected**

It should be consistent to Line Graph.

![image](https://user-images.githubusercontent.com/4908886/61313670-89dc8200-a7c0-11e9-8646-648719ded1df.png)

**Comment by jodybutts** [comment]
@abhijit945 do you mean that in a Paired Results graph with more than 2 variables we should not allow any regions to display? 

In the particular graph you referenced, we are not showing more than one at the same time, only via hover. Plus, when I turn off all but one graph, the region is not displaying for the one that remains.

I think we could treat it just the same as Regions > Line > Multiple line and use the default grey for each, but also display the region when there is only a single variable toggled on. 

What are your thoughts?

**Comment by abhijit945** [comment]
I am not clear what you meant in the original issue on Cerner GH (I moved this issue from there).

**Comment by jodybutts** [comment]
So this was something I had previously logged? I don't remember the context behind it, sorry. Is it possible to see the original chain still?

**Comment by jodybutts** [comment]
After further discussion via Teams, we discussed that only one change is necessary: when all but one data set is toggled off from the legend (note: a data set can contain paired values), the region(s) should appear face up. This is to ensure consistency with the normal line multi-line scenario.

**Comment by abhijit945** [comment]
Updated the defect description.
