### ISSUE TITLE
Gantt leaves behind an empty tooltip at the bottom of the screen

### ISSUE THREAD

**Issue by Matthematic** [cerner/carbon-graphs#306]
**What part of Carbon does this bug correlate to?**
General graph logic:

* [ ]  Graph attributes (axes, legends, regions...etc.)
* [x]  Other (please specify): 

Specific graph logic:

* [ ]  Bar graph
* [ ]  Bubble graph
* [x]  Gantt chart
* [ ]  Line graph
* [ ]  Paired result
* [ ]  Pie chart
* [ ]  Scatter plot
* [ ]  Timeline

**Describe the bug**
There is a tooltip created for Gantt labels using the class "carbon-label-popup-tooltip" that is remaining at the bottom of screen when its not in use. This causes the containing element in our project to overflow and display an unnecessary scrollbar. 

**Link to CodeSandbox**

https://codesandbox.io/s/musing-ganguly-pv7hv?file=/src/graph.js

**Expected behavior**
The tooltip should not be displayed if its not in use.

**Screenshots**
![image](https://user-images.githubusercontent.com/6292111/94950213-dc7a8a80-04a7-11eb-84fd-74408cbbfd49.png)

**Desktop (please complete the following information):**

-   OS: Windows
-   Browser Chrome

**Additional context**

**Comment by Veera81** [comment]
@AshishMotanamGurunadham Is this issue fixed by the PR? https://github.com/cerner/carbon-graphs/pull/302

**Comment by AshishMotanamGurunadham** [comment]
> @AshishMotanamGurunadham Is this issue fixed by the PR? #302

@Veera81 yes #302 PR will fix this issue.

**Comment by Veera81** [comment]
@Matthematic Thanks for logging the issue. Can you take the carbon-graphs version 2.13.6 and see if you still see the same issue?

**Comment by Matthematic** [comment]
@Veera81 It appears to be fixed, thanks!
