### ISSUE TITLE
Remove Git Reference from Master / Released Versions

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/carbon-graphs#313]
**What part of Carbon does this bug correlate to?**
Use released version of `one-cerner-style-icons` or copy forward the current master icon version and remove the git reference: https://github.com/cerner/carbon-graphs/blob/main/package.json#L98

**Comment by mraplumb** [comment]
Looks like this has been in place since the initial 1.0 release of Carbon and never updated.

**Comment by emilyrohrbough** [comment]
Looks like we directly reference the tar in terra-icon: https://github.com/cerner/terra-core/blob/master/packages/terra-icon/package.json#L26

**Comment by sdadn** [comment]
This issue has been resolves as part of:
https://github.com/cerner/terra-graphs/pull/5
