### ISSUE TITLE
Axis overlap for month with 31 days

### ISSUE THREAD

**Issue by abhijit945** [cerner/carbon-graphs#32]
**Describe the bug**
When there is date transition through 31st of a month to the 1st of the next month, then the x-axis tick values deviate from the expected behavior.

![image](https://user-images.githubusercontent.com/4908886/61050420-9326b280-a3ac-11e9-933f-54f28741bce2.png)

In the above screenshot, the two adjacent dates (tick values) are displayed and is also overlappping whereas the expected behavior should same as the one for month with 30 days as shown in the screenshot below
![image](https://user-images.githubusercontent.com/4908886/61050434-9d48b100-a3ac-11e9-99ed-261eb933aa87.png)

Noticed this behavior in the follwing graph types:
1. Line graph 
2. Paired Result Graph

This is a problem in smaller viewport sizes only.

**Comment by nramamurth** [comment]
@abhijit945 

I am curious here. Is it theoretically valid to have different intervals (Mar 31 - Apr 1 being one day, and the rest being 2 days) on an axis in a Line Graph?

**Comment by abhijit945** [comment]
Theoretically sure (If I am not misunderstanding you). Carbon would need to define it as an ordinal scale axis instead of timeseries (i.e. consumers will be free to define axis values as a string, so that it will be possible to define `Jan - Mar`, `Apr - Jun` etc. ). 
One such example is https://bl.ocks.org/pstuffa/c37d059efa1501d33913d63ffe3585db

We also have an enhacement issue logged for this type of axis: https://github.com/cerner/carbon-graphs/issues/11
