### ISSUE TITLE
Update background bar default color

### ISSUE THREAD

**Issue by laurunning** [cerner/carbon-graphs#43]
Update default to gray not blue. 

https://github.cerner.com/Geneva/carbon-graphs/blob/master/docs/controls/Gantt.md#activities

![image](https://user-images.githubusercontent.com/32143728/61158908-f2c1b280-a4bf-11e9-9e2e-2ff90fa4e97e.png)

**Comment by abhijit945** [comment]
Should be pretty straightforward [change](https://github.com/cerner/carbon-graphs/blob/47037dfa0fdbb929993828ef06b242fd4b66bcfa/src/main/js/controls/Gantt/helpers/durationHelpers.js#L28). 

@laurunning Wont this impact current consumers who are using Gantt background bars with `Default` as `Blue`? I have marked this as **breaking** change for now.

**Comment by laurunning** [comment]
I think the default should be gray. Are there any consumers taking this right now?

**Comment by abhijit945** [comment]
We don't have a list of all the consumers that use Carbon right now. I was hoping you would have that info 😞

**Comment by abhijit945** [comment]
Removing the label breaking since this is not a API change but a visual change approved by our standards. 

@laurunning

**Comment by swatikode** [comment]
To clarify are the changes only valid to the duration? What about [task](https://github.com/cerner/carbon-graphs/blob/8d77aa1f7c4b4c8e9ecc0fd803f5cb71055d5e0c/src/main/js/controls/Gantt/helpers/taskHelpers.js#L115) and [activity](https://github.com/cerner/carbon-graphs/blob/8d77aa1f7c4b4c8e9ecc0fd803f5cb71055d5e0c/src/main/js/controls/Gantt/helpers/activityHelpers.js#L47)?

**Comment by abhijit945** [comment]
@laurunning Just confirming, which of these do you want changed to gray by default: https://engineering.cerner.com/carbon-graphs/#/gantt/bar-types

**Comment by abhijit945** [comment]
`I think we should hide the event lines from the other examples and make a separate example page for them so that they aren't competing`
You mean the gray Datelines with Triangles? Do you want to make those Green with Triangles in the separate example we would create instead?

**Comment by abhijit945** [comment]
I am not sure I follow, can you clarify the following: 
* All the default values for Gantt - Tasks, Activities to be Gray color
* What do you mean by `I do think we should pick different colors for activities vs events`?
* Are we changing the terminology for Datelines to Event lines?
* Would this be applicable for Bar graphs? Default is Blue as well.

**Comment by swatikode** [comment]
Based on the UX sync meeting we will keep the default color as blue and not change it to gray. Converting to gray might make it appear as if it was disabled so we are moving away from this idea.
