### ISSUE TITLE
Disabled Legend Item for No Data

### ISSUE THREAD

**Issue by erinplourde** [cerner/carbon-graphs#47]
<img width="549" alt="Screen Shot 2019-07-17 at 11 03 20 AM" src="https://user-images.githubusercontent.com/52933964/61391604-b062f180-a882-11e9-9b09-196b94567c56.png">

Creation of a disabled legend item that can be used with the no data pattern. The disabled legend item is the toggled on legend item but dropped to 35% opacity and the text color is changed to #bfbfbf. The legend item is not interactive in any way (the cursor will not change when hovered on).

**Comment by abhijit945** [comment]
Based on [this](https://wiki.cerner.com/pages/viewpage.action?spaceKey=UserExperience&title=Color%20Palette) I dont see a `#bfbfbf`, the closest one that I could find is `#BCBFC0`. Can we use that?

**Comment by erinplourde** [comment]
Yeah that should work! I will change the call outs to match #bcbfc0!

**Comment by abhijit945** [comment]
Cool, thanks!
