### ISSUE TITLE
Load and unload a batch of rows

### ISSUE THREAD

**Issue by habelk** [cerner/carbon-graphs#51]
Carbon currently supports the addition and removal of rows through loadContent() and unloadContent() functions, but these only accept a single row at a time. It could potentially increase performance if these functions were able to load and unload a batch of rows. 

We tested carbon to load rows in batch and experienced  significantly faster load time on large loads/unloads. For our use case we tested with Gantt graphs.

**Comment by abhijit945** [comment]
You can use this? https://github.com/cerner/carbon-graphs/blob/master/src/main/js/helpers/loadUtil.js#L18

**Comment by habelk** [comment]
Yes, I can use loadUtil.js#L18 for Gantt need. I have it working, can you add privs to create a branch.

**Comment by abhijit945** [comment]
Hi @habelk Can you create fork and add your PR that way? Thanks
