### ISSUE TITLE
Add support to load/unload multiple datasets

### ISSUE THREAD

**Issue by abhijit945** [cerner/carbon-graphs#56]
**Is your feature request related to a problem? Please describe.**
Currently Gantt and Pie (Load only) has implemented this by using `contentLoadHandler` and `contentUnloadHandler` to increase performance when there are large amount of data to be loaded at a time. 

**Describe the solution you'd like**

Implement the same for:

- [ ] Line
- [ ] Paired Result
- [ ] Bar
- [ ] Timeline
- [ ] Pie (_during unload_)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by abhijit945** [comment]
Refer [this](https://github.com/cerner/carbon-graphs/pull/55) PR

**Comment by mjhenkes** [comment]
resolved in terra-graphs pr #28
