### ISSUE TITLE
Y-Axis label empty space issue

### ISSUE THREAD

**Issue by Ashish1109** [cerner/carbon-graphs#57]
**Describe the bug**
As per the carbon's documentation an Y-Axis label is expected behavior and if we do not provide a label it would error out. But if I provide an empty space in the label field(to show only the label icons on the Y-Axis) the label icons gets overlapped with the Y-Axis ranges.

**To Reproduce**
1. Provide an empty space in the label as documented [here](https://github.cerner.com/Geneva/carbon-graphs/blob/master/docs/controls/Line.md#structure)

**Expected behavior**
The label icons should be able to display beside the Y-Axis by providing an empty space in the label field.
![image](https://user-images.githubusercontent.com/18701917/61953687-a9239e00-af7c-11e9-8073-a6d27a95789f.png)
As from the above the image we should be able to display the graph with the label icons on the Y-Axis and without label names(Y1 & Y2) on the Y-Axis.

**Screenshots**
Error screenshot
![image](https://user-images.githubusercontent.com/18701917/61953465-197def80-af7c-11e9-94bc-b3dc666731e4.png)

**Desktop (please complete the following information):**

-   Browser [chrome]

**Additional context**

**Comment by abhijit945** [comment]
As mentioned [here](https://github.cerner.com/Geneva/carbon-graphs/blob/master/docs/helpers/Axes.md#required) labels are required parameter for axes, it is expected for it to throw error when passing blank or null value.

**Comment by abhijit945** [comment]
Please feel free to create an enhancement request [here](https://jira3.cerner.com/secure/RapidBoard.jspa?projectKey=CARBON&rapidView=6001) since this might need requirements change, so that we can handle the design discussion there.
