### ISSUE TITLE
Allow the tasks on Gantt to return custom attributes

### ISSUE THREAD

**Issue by sehsuj** [cerner/carbon-graphs#64]
**Is your feature request related to a problem? Please describe.**
Currently tasks on gantt are returning only few predefined attributes.  Return any custom attributes that are set during task creation. 

**Describe the solution you'd like**
Updated [processTask](https://github.com/cerner/carbon-graphs/blob/master/src/main/js/controls/Gantt/helpers/taskHelpers.js#L96) to return dataTarget object in addition tho the present returning attributes. 

**Describe alternatives you've considered**

**Additional context**

**Comment by abhijit945** [comment]
If this is a feature request, can you use the appropriate template and fill out all the details?
Thanks

**Comment by abhijit945** [comment]
The [value](https://github.com/cerner/carbon-graphs/blob/master/src/main/js/controls/Gantt/helpers/taskHelpers.js#L77) `key` is provided so that consumer can know which task/datapoint is selected by the user. You can depend on that?

**Comment by mrw100** [comment]
We would like to be able to attach some custom data to the task(a type attribute) because we have multiple types of data that get represented as tasks on carbon, but display different content when selected.

**Comment by abhijit945** [comment]
Can you provide more context to this? An example would be nice as well.

**Comment by mrw100** [comment]
Here are two examples of taskConfig objects we would like to send carbon:
Medication Activity Config
`
{
  key: activity.id,
  startDate: activity.dueDateTime,
  endDate: activity.dueDateTime,
  color: '#7A7F82',
  style: { isHollow: true },
  onClick: handleTaskSelected,
  type: 'ACTIVITY',
}
`
Medication Administration Config
`
{
  key: admin.id,
  startDate: admin.startDateTime,
  endDate: admin.startDateTime,
  onClick: handleTaskSelected,
  type: 'ADMINISTRATION',
}
`
Now whenever a task is selected the 'value' that is given to our onClick function will contain the type attribute, which will allow us to check the type and display the correct popup content based on that type.

**Comment by abhijit945** [comment]
Thanks. 
Do both the configs have same `key` (do you control the `key` value?) or is it auto-generated?

I was thinking more like you could namespace which keys belong to which `type` of config and show the respective popup.

**Comment by mrw100** [comment]
We did consider that but felt it would be better to have a specific attribute instead of having to parse the type off the key. We have the ability the added custom attributes on the track config, so we would really just be making the behavior consistent. 

@sehsuj is going to have a prototype available soon to show you the change that we would make

**Comment by sehsuj** [comment]
@abhijit945  [here](https://github.cerner.com/AJ046020/carbon-graphs/commit/a53d8308ca8210547bdc8d759c65a8cd792f0c05) the change that we would like to make.

**Comment by abhijit945** [comment]
For reference, 
![image](https://user-images.githubusercontent.com/4908886/63186417-f6e27200-c021-11e9-925e-fb87edff17d1.png)

I do **not** think I am for this enhancement to be implemented within Carbon. 
Primary reason being that Carbon is deepcloning the input object provided by the consumer to process the data and works pretty heavily with that object. Having arbitrary number of properties being provided by consumer (that only works as a passthrough) without having any impact on the graph itself is not something that we are willing to take on right now.

We also dont want to take the risk of some internal properties being overwritten with the properties provided by the consumer.

**Comment by Matthematic** [comment]
It seems you are taking that risk on the [track config](https://github.com/cerner/carbon-graphs/blob/master/src/main/js/controls/Gantt/Track.js#L123) already. Was this a mistake?
