### ISSUE TITLE
Gantt chart start, end date points differs from mentioned lowerLimit, upperLimit date

### ISSUE THREAD

**Issue by nn052161** [cerner/carbon-graphs#65]
**Describe the bug**
Carbon Gantt chart start and endpoints differ from the dates that are mentioned in upper and lower limits.

**To Reproduce**
Add lowerLimit: "2019-06-05T05:00:00.000Z", upperLimit: "2019-08-19T18:03:50.557Z" for gantt chart x axis.

**Expected behavior**
Gantt chart start date should be the date I give in the lower limit, in this case, June 5th and end date should be Aug 19th as it is the upper limit that I mentioned.

**Screenshots**
![GanttChart](https://user-images.githubusercontent.com/54286765/63289577-11685580-c285-11e9-82d0-f8bb1c6a7a00.png)

**Desktop (please complete the following information):**
-   OS: IOS
-   Browser Chrome

**Additional context**

**Comment by abhijit945** [comment]
This is due to Range Rounding when using `nice()`. This feature is enabled by default. To turn it `off` you can use [this](https://github.com/cerner/carbon-graphs/blob/master/docs/helpers/Axes.md#optional) optional parameter and set it to `false`.

**Comment by abhijit945** [comment]
Created an issue to update Gantt docs with `rangeRounding` flag. 
https://github.com/cerner/carbon-graphs/issues/66

**Comment by nn052161** [comment]
Rounding logic can make a change but not fixing what I need. I want the chart to start from Jun 07th and end by Aug 19th. Without rounding logic I'm losing the preciseness. Even though before Jun 9th there is a block, I can't assure whats the starting date. Whether it started from Jun 6th or Jun 7th or 8th. The same for the end date.

**Comment by abhijit945** [comment]
Once you set the flag to `false` it will. 
Here is more information about [d3.nice](https://d3-wiki.readthedocs.io/zh_CN/master/Time-Scales/#nice)

**Comment by nn052161** [comment]
I understand if I set rangeRounding flag to false, it satisfies our scenario. But is there any way to make the chart show start and end labels. Right now My lower limit is June 07th and bar started from right before June 09th. As I know the lower limit, I can assume it started from June 07th. But if someone checks the chart they are not sure about the Start date. 
![Screen Shot 2019-08-21 at 10 55 50 AM](https://user-images.githubusercontent.com/54286765/63448300-40a4d100-c403-11e9-86da-aec3fd238dca.png)

**Comment by abhijit945** [comment]
That was the reason why we added rangeRounding, to enforce d3 to show first and last ticks.
For instance,

**Range:** `[ 0.153, 0.987 ]`

Simple X axis **using** nice: https://jsbin.com/wivemit/3/edit?html,output
![image](https://user-images.githubusercontent.com/4908886/63449150-1bb15d80-c405-11e9-802a-e3d3e7ba116f.png)

Simple X axis **without using** nice: https://jsbin.com/zigivas/4/edit?html,output
![image](https://user-images.githubusercontent.com/4908886/63449176-31268780-c405-11e9-9d48-cb8a88c39833.png)

**Comment by nn052161** [comment]
I want x-axis to show 0.15 and 0.98 labels instead of its rounding vales. Is there any way to make it show

**Comment by abhijit945** [comment]
Yup, you can use `ticks` object as mentioned [here](https://github.com/cerner/carbon-graphs/blob/master/docs/helpers/Axes.md#optional)
Provide any values like so:
```js
axis: {
                x: {
                    show: true,
                    label: "Data",
                    lowerLimit: 80,
                    upperLimit: 280,
                    ticks: {
                        format: "", // Make sure you provide a format to show
                        values: [] // Add any values here
                    }
                }
```
