### ISSUE TITLE
Outliers/Viewable area 

### ISSUE THREAD

**Issue by laurunning** [cerner/carbon-graphs#74]
There are cases in which including all data points face up will impact the usability/interpretation of the lines. Outliers could impact the slope of the line causing it to be very flat and unusable. This request is to show a viewable area based on fixed ranges and if data points appear outside of that indicate to the user that there are points outside the viewable area via running the line off the edge of the viewable area paired with a banner notifying the user of the data outside of the viewable graph. 

**Reasoning:** The reason we wanted to avoid showing all data points is change blindness. If the user had a standard graph view they used for every patient, but the y-axes were slightly different from patient to patient, they might not see the change in axis values and could rely on the slope of the line instead. If points appear off the edge of the graph, drawn lines themselves are indication enough since they go out of the current view. Allowing the user to access what those points are is necessary for them either in progressive disclosure. 

![image](https://user-images.githubusercontent.com/32143728/66857110-34914780-ef4c-11e9-919d-ed6a4338dd59.png)

**Comment by laurunning** [comment]
Additionally - we believe we need a banner notification to alert users that there are outlier data points and how to access them. 

This flag doesn't have to be built out for all instances. If there is a set view we need this to combat change blindness. If the y-axis consistent patient to patient, this is a necessary safeguard. A graph with the same variables looking for the same line pattern across patients' charts is a valid use case and if the y-axis is changing, this leads to concerning change blindness.

If the end user is defining the variables on the fly for the graph then this is not necessary. For these cases we can show all data face up.

**Comment by laurunning** [comment]
This will not have the scroll bar. This is for verified data. We also need additional documentation for users implementing this that they need to include the banner.

**Comment by abhijit945** [comment]
I have few questions: 

> The reason we wanted to avoid showing all data points is change blindness

* Isnt this applicable for all current consumers using graphs? 
* Does this mean that our solution of providing consumers with functionality of Reference Ranges and Criticality indicators are no longer valid?

> We also need additional documentation for users implementing this that they need to include the banner.

We will **require** consumers to implement the banner to prevent any loss of context. Even with extensive documentation, we cannot assure this.

**Comment by laurunning** [comment]
1. If the y-axis consistent patient to patient, this is a necessary safeguard. A graph with the same variables looking for the same line pattern across patients' charts is a valid use case and if the y-axis is changing, this leads to concerning change blindness. If the end user is defining the variables on the fly for the graph then this is not necessary. For these cases we can show all data face up.

2. No, those are still valid and helpful but this is additional functionality that will make for a more safe experience in these cases. Jody had done research in this area for her UX talk on safety with data viz. 

3. True, we cannot confirm that they do this, but would like to include as many preventions as we can.

**Comment by abhijit945** [comment]
Hmm I dont feel comfortable with giving a thumbs up here. A graph is supposed to show a data point that was provided. If the datapoint has a freak value then the consumer has the decision to make -> either filter it or show it faceup with a criticality indicator. Not showing the value and expecting the consumer will remember to read the documentation and implement/show the banner is not a risk a library should be willing to take. 
As a library we should ship a complete functionality. 

But I will leave others to weigh in and decide if this should be taken forward.
@ryanthemanuel 
@benbcai 
@swatikode 
@crystalhaley 
@avinashg1994 
@ShettyAkarsh

**Comment by laurunning** [comment]
Hi, I forgot to add a very key component to this issue - the ability to launch out to a full-page view of the graph with an axis that spans the full height of the data. This part of the proposal was something Katie P. designed in the past. For example:
![image](https://user-images.githubusercontent.com/32143728/66936606-9bbe0300-f003-11e9-9dfb-2d08d6eb8cfc.png)
![image](https://user-images.githubusercontent.com/32143728/66936621-a4163e00-f003-11e9-8e56-d19e4b8f268a.png)
