### ISSUE TITLE
Hide axis on timeline for integration with timeline navigations

### ISSUE THREAD

**Issue by laurunning** [cerner/carbon-graphs#92]
Ability to hide the axis on timeline so that we can integrate with any timeline navigations/frameworks. It would look like this:
![image](https://user-images.githubusercontent.com/32143728/65979017-40ecaf00-e43a-11e9-9e30-7238f3d5e52e.png)

**Comment by abhijit945** [comment]
Will be part of 
![image](https://user-images.githubusercontent.com/4908886/65982476-0afef900-e441-11e9-8594-a46da54fa2ce.png)

**Comment by laurunning** [comment]
Ticks should still show - but just the tick labels should be hidden. Is that possible?

**Comment by abhijit945** [comment]
Sounds good.

**Comment by abhijit945** [comment]
Hi @laurunning 
How many consumers are asking for this? Depending on your answer we can decide on the approach on how to handle this. 

I am wondering if its a **single consumer** then we can advice them to just override the CSS classes. 
_Hide Tick values:_
```css
.carbon-axis.carbon-axis-x .tick text {
    display: none;
}
```
![image](https://user-images.githubusercontent.com/4908886/66132299-71f3ed80-e5ba-11e9-8906-0cd1820d181f.png)

_Hide Tick lines:_ 
```css
.carbon-axis.carbon-axis-x .tick line {
    display: none;
}
```
![image](https://user-images.githubusercontent.com/4908886/66132346-87691780-e5ba-11e9-93cf-d202d3df60af.png)


If there are **more consumers** then we can add **flags** to trigger these behavior for ease.

**Comment by laurunning** [comment]
We discussed in the sync on 10.4.19 - For theming considerations, a consistent flag is a better long term strategy.

**Comment by crystalhaley** [comment]
Is there a CARBON JIRA associated to this?

**Comment by abhijit945** [comment]
I dont think we need reqs for this. Consumer can just pass blank to _hide_ the tick labels. Your call.

**Comment by crystalhaley** [comment]
Sorry... pushed the "close" button by accident. You would think there would be some kind of "Are you sure?" dialog.
